server:
  port: 8080
  tomcat:
    threads:
      max: 2000
    max-connections: 2000
  servlet:
    context-path: /taskapp

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


spring:
  flyway:
    enabled: true
    locations: classpath:db/migration
    validate-on-migrate: true

  datasource:
    url: jdbc:postgresql://localhost:5432/taskapp
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50
      initialization-fail-timeout: 0


  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true

logging:
  level:
    org.springframework.boot.autoconfigure.flyway: DEBUG
