server:
  port: 8080
  tomcat:
    threads:
      max: 2000
    max-connections: 2000
  servlet:
    context-path: /taskapp

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/taskapp
    username: admin
    password: admin
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50
      initialization-fail-timeout: 0

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
    hibernate:
      ddl-auto: create-drop

  sql:
    init:
      schema-locations: classpath:init.sql
      mode: always



#logging:
#  level:
#    org.hibernate.SQL: DEBUG
#    org.hibernate.type.descriptor.sql.BasicBinder: TRACE