server:
  port: 8080
  tomcat:
    threads:
      max: 2000
    max-connections: 2000
  servlet:
    context-path: /taskapp

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html


spring:
  flyway:
    enabled: ${SPRING_FLYWAY_ENABLED:true}
    locations: classpath:db/migration
    validate-on-migrate: true

  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/taskapp}
    username: ${SPRING_DATASOURCE_USERNAME:admin}
    password: ${SPRING_DATASOURCE_PASSWORD:admin}
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 100
      minimum-idle: 50
      initialization-fail-timeout: 0


  jpa:
    hibernate:
      ddl-auto: none
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        jdbc:
          batch_size: 100

  security:
    oauth2:
      client:
        registration:
            google:
                client-id: ${GOOGLE_CLIENT_ID:430743706570-rh1rc6gppdshtjbnl136vhgcfu5tvfrk.apps.googleusercontent.com}
                client-secret: ${GOOGLE_CLIENT_SECRET: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}
                scope:
                - openid
                - profile
                - email
                redirect-uri: "${GOOGLE_REDIRECT_URI:{baseUrl}/login/oauth2/code/{registrationId}}"
                client-name: Google
        provider:
            google:
                issuer-uri: https://accounts.google.com

logging:
  level:
    org.springframework.boot.autoconfigure.flyway: DEBUG

app:
  frontend:
    popup-origin: ${FRONTEND_POPUP_ORIGIN:http://localhost}
    base-url: ${FRONTEND_BASE_URL:http://localhost}
  backend:
    base-url: ${BACKEND_BASE_URL:http://localhost:8080}
  jwt:
    issuer: ${JWT_ISSUER:https://auth.taskapp.local}
    access-token-minutes: ${JWT_ACCESS_TOKEN_MINUTES:15}
    refresh-token-days: ${JWT_REFRESH_TOKEN_DAYS:14}
    key:
      kid: ${JWT_KEY_ID:taskapp-key-1}
      private: classpath:keys/privateKey.pem
      public: classpath:keys/publicKey.pem