services:
  postgres:
    image: postgres:15.1-alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init:/docker-entrypoint-initdb.d  # Mount init scripts

  back:
    build:
      context: ./taskapp-back
      dockerfile: Dockerfile
    image: taskapp-back:latest
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/taskapp
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin
      SPRING_FLYWAY_ENABLED: "true"
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    restart: unless-stopped

  front:
    build:
      context: ./taskapp-front
      dockerfile: Dockerfile
    image: taskapp-front:latest
    ports:
      - "3000:3000"
    depends_on:
      - back
    restart: unless-stopped


volumes:
  postgres_data:



#  keycloak:
#    image: quay.io/keycloak/keycloak:26.0
#    command: ["start-dev"]
#    environment:
#      KC_DB: postgres
#      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
#      KC_DB_USERNAME: postgres
#      KC_DB_PASSWORD: postgres
#      KEYCLOAK_ADMIN: admin
#      KEYCLOAK_ADMIN_PASSWORD: admin
#    ports:
#      - "8081:8080"
#    depends_on:
#      - postgres
#    restart: unless-stopped
#
#  wso2apim:
#    image: wso2/wso2am:latest
#    container_name: wso2apim
#    ports:
#      - "9443:9443"   # Console/Publisher/Dev Portal (HTTPS)
#      - "8243:8243"   # API Gateway (HTTPS)
#      - "8280:8280" #
#    extra_hosts:
#      - "host.docker.internal:host-gateway"  #  APIM call API on host Linux
#    depends_on:
#      - keycloak
#    restart: unless-stopped
