replicaCount: 2

image:
  repository: <your-account-id>.dkr.ecr.eu-west-3.amazonaws.com/taskapp-back
  pullPolicy: IfNotPresent
  tag: "latest"

service:
  type: LoadBalancer
  port: 80

env:
  SPRING_DATASOURCE_URL: jdbc:postgresql://rds-prod-taskapp.cvwkycmmmr2u.eu-west-3.rds.amazonaws.com:5432/taskapp
  SPRING_DATASOURCE_USERNAME: postgres
  SPRING_DATASOURCE_PASSWORD: postgres123
  SPRING_FLYWAY_ENABLED: "true"

secrets:
  rds_password: postgres123