apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "backend.fullname" . }}
  labels:
    {{- include "backend.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "backend.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "backend.labels" . | nindent 8 }}
        {{- with .Values.podLabels }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          ports:
            - name: http
              containerPort: {{ .Values.service.port }}
          env:
            - name: FRONTEND_POPUP_ORIGIN
              value: {{ .Values.env.FRONTEND_POPUP_ORIGIN }}
            - name: FRONTEND_BASE_URL
              value: {{ .Values.env.FRONTEND_BASE_URL }}
            - name: BACKEND_BASE_URL
              value: {{ .Values.env.BACKEND_BASE_URL }}
            - name: JWT_ISSUER
              value: {{ .Values.env.JWT_ISSUER }}

            - name: SPRING_DATASOURCE_URL
              value: {{ .Values.env.SPRING_DATASOURCE_URL }}
            - name: SPRING_DATASOURCE_USERNAME
              value: {{ .Values.env.SPRING_DATASOURCE_USERNAME }}
            - name: SPRING_DATASOURCE_PASSWORD
              value: {{ .Values.env.SPRING_DATASOURCE_PASSWORD }}
            - name: SPRING_FLYWAY_ENABLED
              value: {{ .Values.env.SPRING_FLYWAY_ENABLED }}

