name: Frontend CI → Build & Deploy to S3 + CloudFront

on:
  push:
    branches: [ "main" ]
    paths:
      - "taskapp-front/**"
      - ".github/workflows/frontend-ci.yml"
  pull_request:
    branches: [ "main" ]
    paths:
      - "taskapp-front/**"

permissions:
  id-token: write
  contents: read

env:
  AWS_REGION: eu-west-3
  S3_BUCKET_FRONTEND: taskapp-frontend-prod   # ví dụ: taskapp-front-prod-site
  CLOUDFRONT_DISTRIBUTION_ID: EXXXXXX123456

concurrency:
  group: frontend-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: taskapp-front
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"
          cache-dependency-path: taskapp-front/package-lock.json

      - name: Install deps
        run: npm ci

      - name: Build
        run: npm run build

      - name: Upload build artifact (optional)
        uses: actions/upload-artifact@v4
        with:
          name: frontend-build
          path: taskapp-front/build

  deploy:
    needs: build
    if: github.event_name == 'push' && github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    steps:
      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: frontend-build
          path: build

      - name: Configure AWS credentials via OIDC
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: arn:aws:iam::864230187726:role/taskapp-ci-cd
          aws-region: ${{ env.AWS_REGION }}

      - name: Sync to S3
        run: |
          aws s3 sync ./build "s3://${{ env.S3_BUCKET_FRONTEND }}" \
            --delete \
            --cache-control "public, max-age=31536000" \
            --exclude "index.html"
          # index.html không nên cache dài
          aws s3 cp ./build/index.html "s3://${{ env.S3_BUCKET_FRONTEND }}/index.html" \
            --cache-control "no-cache, no-store, must-revalidate" \
            --content-type "text/html"

#      - name: Invalidate CloudFront
#        run: |
#          aws cloudfront create-invalidation \
#            --distribution-id "${{ env.CLOUDFRONT_DISTRIBUTION_ID }}" \
#            --paths "/*"
