name: Maven Package

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:

  build_maven:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build with Maven
        run: |
          cd taskapp-back
          mvn -B package --file pom.xml

  build_react:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install dependencies (React)
        run: |
          cd taskapp-front
          npm install

